server.port=${PORT:8085}
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=false

# ?? ? MongoDB ?? ? ??? ????? ??? ? ???!
spring.data.mongodb.uri=mongodb+srv://minkook0202_db_user:${MONGODB_PASSWORD}@cluster0.nuv53xm.mongodb.net/tacoclouddb