spring.application.name=lec20
server.port=8085
spring.thymeleaf.cache=false


spring.datasource.generate-unique-name=false

spring.data.mongodb.uri=mongodb+srv://minkook0202_db_user:momk032105*@cluster0.nuv53xm.mongodb.net/tacoclouddb


spring.datasource.name=tacocloud
spring.devtools.restart.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/tacocloud?serverTimezone=UTC&characterEncoding=UTF-8

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mymk032105*

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
