server.port=${PORT:8085}
spring.thymeleaf.cache=false

# MongoDB ??
spring.data.mongodb.uri=mongodb+srv://minkook0202_db_user:${MONGODB_PASSWORD}@cluster0.nuv53xm.mongodb.net/tacoclouddb


## Render ?? ??? SPRING_DATASOURCE_URL? ??? ??? ??, ??? ?? MySQL? ?????.
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tacocloud?serverTimezone=UTC&characterEncoding=UTF-8}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# [??] Dialect? ????? ???? ?????? ?? ??
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

